<a href="https://colab.research.google.com/github/Sayantani1903/Python_Assignment/blob/main/NumPy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Q-1 Explain the purpose and advantages of NumPy in scientific computing and Data Analysis.How does it enhance Python's capabilities for numerical operations?**

NumPy, which stands for Numerical Python, is a powerful library that serves as the foundation for numerical computing in Python. Its purpose and advantages in scientific computing and data analysis include:

### Purpose of NumPy
1. **Efficient Array Operations**: NumPy provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.
2. **Performance Optimization**: It allows for vectorized operations, enabling faster computation compared to traditional Python lists, especially for large datasets.
3. **Mathematical Functions**: NumPy includes a range of mathematical functions for performing operations like linear algebra, Fourier transforms, and random number generation.

### Advantages of NumPy
1. **Speed**: NumPy’s operations are implemented in C, making them much faster than equivalent Python code, especially for large datasets.
2. **Memory Efficiency**: It uses contiguous blocks of memory for its arrays, which can lead to better cache performance and lower memory overhead.
3. **Convenient Syntax**: NumPy's syntax is designed for ease of use, allowing for concise and readable code. Operations on arrays can often be performed with a single line of code.
4. **Interoperability**: NumPy integrates seamlessly with other scientific computing libraries like SciPy, pandas, and Matplotlib, allowing for comprehensive data analysis and visualization workflows.
5. **Broadcasting**: This powerful feature allows operations between arrays of different shapes, which can simplify coding and enhance performance.
6. **Support for Complex Data**: NumPy supports complex numbers and provides tools for complex numerical computations, which is essential in many scientific fields.

### Enhancements to Python's Capabilities
1. **Array Objects**: NumPy introduces the `ndarray` (n-dimensional array) object, which is more efficient than native Python lists for numerical operations.
2. **Advanced Indexing and Slicing**: NumPy offers sophisticated methods for indexing and slicing arrays, allowing for efficient data manipulation and retrieval.
3. **Mathematical Functions**: It provides a wide range of mathematical functions that can be applied to arrays, allowing for complex operations without the need for explicit loops.
4. **Linear Algebra and Statistics**: NumPy has built-in support for linear algebra operations (like matrix multiplication) and statistical functions, making it easier to perform these tasks directly in Python.

In summary, NumPy enhances Python's capabilities for numerical operations by providing efficient array handling, a wealth of mathematical functions, and features that promote performance and readability, making it an essential tool for scientific computing and data analysis.

Q-2 **Compare and contrast no.mean() and np.average() functions in NumPy. When would you use one over the other?**

In [ ]:
'''The `np.mean()` and `np.average()` functions in NumPy both serve to calculate averages,
 but they have some key differences in their functionality and use cases.'''

### `np.mean()`
'''Purpose: Computes the arithmetic mean (average) of the elements along a specified axis.
Syntax: `np.mean(a, axis=None, dtype=None, out=None, keepdims=False)`
Default Behavior: Calculates the mean of all elements if no axis is specified.'''
#Usage:
'''- Ideal for straightforward mean calculations across arrays.
  - Less flexible, as it does not accommodate weights for the elements.'''

### `np.average()`
'''Purpose: Computes the weighted average of the elements along a specified axis.
Syntax: `np.average(a, axis=None, weights=None, returned=False)`
Weights: Allows you to specify a weights array to give different importance to different elements in the calculation.
Default Behavior: If weights are not specified, it behaves like `np.mean()`.'''
#Usage:
'''- Use when you need to calculate a weighted average, where some values contribute more significantly than others.
  - Provides flexibility with the `weights` parameter.'''

### When to Use Each
# Use `np.mean()` when:
'''- You want a simple average without any weighting considerations.
  - You are performing standard mean calculations on data without the need for custom weighting.'''

#Use `np.average()` when:
'''- You need to account for the importance of different values (weighted average).
  - You want to control how much influence each element has on the overall average.'''

### Example

import numpy as np

data = np.array([1, 2, 3, 4])

# Using np.mean
mean_value = np.mean(data)  # Result: 2.5

# Using np.average without weights
average_value = np.average(data)  # Result: 2.5

# Using np.average with weights
weights = np.array([1, 1, 1, 4])  # Giving more weight to the last element
weighted_average = np.average(data, weights=weights)  # Result: 3.0


'''In summary, choose `np.mean()` for straightforward mean calculations and `np.average()` when you need to incorporate weights into your average.'''

'In summary, choose `np.mean()` for straightforward mean calculations and `np.average()` when you need to incorporate weights into your average.'

Q-3**Describe the methods for reversing a NumPy array along along different axes. Provide examples for 1D and 2D arrays.**

In [ ]:
'''Reversing a NumPy array can be done using slicing or the `np.flip()` function,
both of which allow you to specify the axes along which to reverse the elements.'''
#Here’s how to do it for both 1D and 2D arrays.

### Reversing a 1D Array

#### Using Slicing
#You can reverse a 1D array by using slicing with a step of `-1`.


import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse using slicing
reversed_arr_1d = arr_1d[::-1]

print("Original 1D array:", arr_1d)
print("Reversed 1D array:", reversed_arr_1d)


### Reversing a 2D Array

#### Reversing Along a Specific Axis
#1.Reversing Rows (Vertical Flip): Use `np.flip()` or slicing to reverse the order of rows.


# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse along the first axis (rows)
reversed_rows = np.flip(arr_2d, axis=0)
# Alternatively: reversed_rows = arr_2d[::-1]

print("Original 2D array:")
print(arr_2d)
print("Reversed 2D array along rows:")
print(reversed_rows)


#2.Reversing Columns (Horizontal Flip): You can reverse the order of columns by flipping along the second axis.


# Reverse along the second axis (columns)
reversed_columns = np.flip(arr_2d, axis=1)
# Alternatively: reversed_columns = arr_2d[:, ::-1]

print("Reversed 2D array along columns:")
print(reversed_columns)


#3.Reversing Both Axes: You can reverse both rows and columns at once.


# Reverse along both axes
reversed_both = np.flip(arr_2d)

print("Reversed 2D array along both axes:")
print(reversed_both)


### Summary
'''For a **1D array**, use slicing `[::-1]` to reverse.
For a **2D array**, use `np.flip(array, axis=0)` to reverse rows, `np.flip(array, axis=1)` for columns,
or simply use `np.flip(array)` to reverse both axes.'''

#These methods provide a flexible way to manipulate and reverse arrays in NumPy efficiently.

Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]
Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed 2D array along rows:
[[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed 2D array along columns:
[[3 2 1]
 [6 5 4]
 [9 8 7]]
Reversed 2D array along both axes:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


'For a **1D array**, use slicing `[::-1]` to reverse.\nFor a **2D array**, use `np.flip(array, axis=0)` to reverse rows, `np.flip(array, axis=1)` for columns,\nor simply use `np.flip(array)` to reverse both axes.'

Q-4 **How can you determine the data type of elements in a NumPy array? Discuss the importance of Data types in memory management and performance.**

In [ ]:
'''You can determine the data type of elements in a NumPy array using the `.dtype` attribute.
This attribute returns a `numpy.dtype` object, which describes the type of data held in the array.'''

### Example of Determining Data Type


import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4])

# Check the data type
data_type = arr.dtype
print("Data type of the array:", data_type)


### Importance of Data Types

#1.Memory Management:
'''Different data types consume different amounts of memory. For instance,
an `int32` consumes 4 bytes, while an `int64` consumes 8 bytes.
Using an appropriate data type can significantly reduce memory usage, especially in large arrays.
For example, if you only need integers between 0 and 255, using `np.uint8` (1 byte) instead of `np.int64` (8 bytes) can save substantial memory.'''

#2.Performance:
'''Operations on arrays with smaller data types can be faster because less data needs to be moved and processed in memory.
NumPy operations are optimized for specific data types. For example,
operations on `float32` arrays are generally faster than on `float64` arrays due to lower memory bandwidth requirements.'''

#3.Precision and Range:
'''Choosing the right data type affects the precision and range of values that can be represented.
For instance, using `float32` might lead to precision loss for very large or very small numbers compared to `float64`.
For integer types, using `np.int16` might cause overflow if values exceed the maximum representable range.'''

#4.Interoperability:
'''Data types ensure compatibility with other libraries or systems that might expect data in specific formats. For example,
when interfacing with C/C++ code or other scientific libraries, maintaining the correct data type is crucial.'''

#Conclusion

'''Understanding and properly managing data types in NumPy arrays is essential for optimizing memory usage and enhancing performance.
By choosing appropriate data types, you can ensure efficient computation and prevent issues related to overflow or precision loss.'''

Data type of the array: int64


'Understanding and properly managing data types in NumPy arrays is essential for optimizing memory usage and enhancing performance. \nBy choosing appropriate data types, you can ensure efficient computation and prevent issues related to overflow or precision loss.'

Q-5 **Define ndarrays in NumPy and explain their key features . How do they differ from  standard Python lists?**

In [ ]:
'''NumPy arrays offer several performance benefits over standard Python lists,
particularly when it comes to large-scale numerical operations. Here’s a detailed analysis of these advantages:'''

### 1.Memory Efficiency
'''Contiguous Memory Allocation: NumPy arrays are stored in contiguous blocks of memory,
which reduces memory fragmentation and improves cache performance. This leads to faster access times compared to Python lists,
 which can store references to objects scattered across memory.
Data Type Homogeneity: All elements in a NumPy array are of the same data type, allowing for optimized memory usage.
In contrast, Python lists can hold different data types, which incurs additional overhead.'''

### 2.Speed of Operations
'''Vectorized Operations: NumPy allows for vectorized operations, meaning that operations can be applied to entire arrays
without explicit loops.
This can lead to significant performance improvements because the operations are executed at the C level,
avoiding the overhead of Python’s interpreted loop execution.
Batch Processing: Operations on arrays are performed in batches, leveraging low-level optimizations and CPU vectorization (SIMD instructions)
to speed up computations, particularly for large datasets.'''

### 3.Reduced Overhead
'''Less Function Call Overhead: When performing operations on NumPy arrays,
the overhead associated with function calls is minimized. This is especially beneficial in loops,
where the cost of repeatedly calling a function can add up significantly.
Built-in Functions: NumPy provides a rich set of optimized mathematical functions that are implemented in C,
which can lead to performance gains over writing custom Python functions for similar tasks.'''

### 4.Broadcasting
'''Efficient Operations on Arrays of Different Shapes: NumPy’s broadcasting feature allows for arithmetic operations on arrays of
different shapes without the need for explicit replication of data.
This leads to more memory-efficient and faster calculations compared to manually adjusting the sizes of Python lists.'''

### 5.Parallelism and Optimizations
#Underlying Libraries:
'''NumPy operations often leverage optimized libraries like BLAS and LAPACK,
which are highly tuned for performance on large arrays. These libraries can utilize multi-threading and other optimizations that
Python’s standard list operations do not.'''

### 6.Ease of Integration with Other Libraries
'''Interoperability with Scientific Libraries**: Many scientific libraries (e.g., SciPy, pandas, Matplotlib)
are built on top of NumPy and are optimized for NumPy arrays.
Using NumPy arrays allows for seamless integration and enhanced performance across these libraries.'''

### Performance Comparison Example

#Here’s a simple performance comparison between NumPy arrays and Python lists for a large-scale numerical operation:


import numpy as np
import time

# Define the size of the array
size = 10**6

# Python list
list_data = list(range(size))

# NumPy array
array_data = np.arange(size)

# Measure time for sum operation using Python list
start_time = time.time()
list_sum = sum(list_data)
print("Python list sum time:", time.time() - start_time)

# Measure time for sum operation using NumPy array
start_time = time.time()
array_sum = np.sum(array_data)
print("NumPy array sum time:", time.time() - start_time)

### Conclusion

'''The performance benefits of NumPy arrays over Python lists become particularly evident in large-scale numerical operations,
where memory efficiency, speed of operations, reduced overhead, and optimized functionalities provide significant advantages.
For tasks involving large datasets or complex mathematical computations,
using NumPy is highly recommended to achieve better performance and efficiency.'''

Python list sum time: 0.007214784622192383
NumPy array sum time: 0.0040094852447509766


'The performance benefits of NumPy arrays over Python lists become particularly evident in large-scale numerical operations,\nwhere memory efficiency, speed of operations, reduced overhead, and optimized functionalities provide significant advantages.\nFor tasks involving large datasets or complex mathematical computations, \nusing NumPy is highly recommended to achieve better performance and efficiency.'

Q-6 **Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.**

In [ ]:
'''NumPy arrays offer several performance benefits over standard Python lists,
particularly when it comes to large-scale numerical operations.'''
#Here’s a detailed analysis of these advantages:

### 1. **Memory Efficiency**
'''Contiguous Memory Allocation: NumPy arrays are stored in contiguous blocks of memory,
which reduces memory fragmentation and improves cache performance.
This leads to faster access times compared to Python lists, which can store references to objects scattered across memory.
Data Type Homogeneity: All elements in a NumPy array are of the same data type, allowing for optimized memory usage.
In contrast, Python lists can hold different data types, which incurs additional overhead.'''

### 2. **Speed of Operations**
'''Vectorized Operations: NumPy allows for vectorized operations, meaning that operations can be applied to entire arrays
without explicit loops. This can lead to significant performance improvements because the operations are executed at the C level,
avoiding the overhead of Python’s interpreted loop execution.
Batch Processing: Operations on arrays are performed in batches, leveraging low-level optimizations and CPU vectorization (SIMD instructions)
to speed up computations, particularly for large datasets.'''

### 3. **Reduced Overhead**
'''Less Function Call Overhead: When performing operations on NumPy arrays, the overhead associated with function calls is minimized.
This is especially beneficial in loops, where the cost of repeatedly calling a function can add up significantly.
Built-in Functions: NumPy provides a rich set of optimized mathematical functions that are implemented in C,
which can lead to performance gains over writing custom Python functions for similar tasks.'''

### 4. **Broadcasting**
'''Efficient Operations on Arrays of Different Shapes:
NumPy’s broadcasting feature allows for arithmetic operations on arrays of different shapes without the need for explicit replication of data.
This leads to more memory-efficient and faster calculations compared to manually adjusting the sizes of Python lists.'''

### 5. **Parallelism and Optimizations**
'''Underlying Libraries: NumPy operations often leverage optimized libraries like BLAS and LAPACK,
which are highly tuned for performance on large arrays.
These libraries can utilize multi-threading and other optimizations that Python’s standard list operations do not.'''

### 6.Ease of Integration with Other Libraries
'''Interoperability with Scientific Libraries:
Many scientific libraries (e.g., SciPy, pandas, Matplotlib) are built on top of NumPy and are optimized for NumPy arrays.
Using NumPy arrays allows for seamless integration and enhanced performance across these libraries.'''

### Performance Comparison Example

#Here’s a simple performance comparison between NumPy arrays and Python lists for a large-scale numerical operation:

import numpy as np
import time

# Define the size of the array
size = 10**6

# Python list
list_data = list(range(size))

# NumPy array
array_data = np.arange(size)

# Measure time for sum operation using Python list
start_time = time.time()
list_sum = sum(list_data)
print("Python list sum time:", time.time() - start_time)

# Measure time for sum operation using NumPy array
start_time = time.time()
array_sum = np.sum(array_data)
print("NumPy array sum time:", time.time() - start_time)

### Conclusion

'''The performance benefits of NumPy arrays over Python lists become particularly evident in large-scale numerical operations,
where memory efficiency, speed of operations, reduced overhead, and optimized functionalities provide significant advantages.
For tasks involving large datasets or complex mathematical computations,
using NumPy is highly recommended to achieve better performance and efficiency.'''

Python list sum time: 0.008241415023803711
NumPy array sum time: 0.001764535903930664


'The performance benefits of NumPy arrays over Python lists become particularly evident in large-scale numerical operations, \nwhere memory efficiency, speed of operations, reduced overhead, and optimized functionalities provide significant advantages.\nFor tasks involving large datasets or complex mathematical computations, \nusing NumPy is highly recommended to achieve better performance and efficiency.'

Q-7 **Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.**

In [ ]:
'''In NumPy, `vstack()` and `hstack()` are functions used to stack arrays vertically and horizontally, respectively.
Here's a breakdown of each function, along with examples demonstrating their usage.'''

### `vstack()`
'''Purpose: Stacks arrays vertically (row-wise).
Input: Arrays must have the same number of columns.'''

#### Example:
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Stack arrays vertically
result_vstack = np.vstack((array1, array2))

print("vstack result:")
print(result_vstack)



### `hstack()`
'''Purpose: Stacks arrays horizontally (column-wise).
Input: Arrays must have the same number of rows.'''

#### Example:

# Create two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Stack arrays horizontally
result_hstack = np.hstack((array1, array2))

print("hstack result:")
print(result_hstack)


### Summary
'''`vstack()`combines arrays by adding rows, producing more rows and the same number of columns.
`hstack()`combines arrays by adding columns, producing more columns and the same number of rows.'''

#Both functions are useful for combining datasets in different orientations based on your needs.

vstack result:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack result:
[[1 2 5 6]
 [3 4 7 8]]


'`vstack()`combines arrays by adding rows, producing more rows and the same number of columns.\n`hstack()`combines arrays by adding columns, producing more columns and the same number of rows.'

Q-8 **Explain the differences between fliplr() and flipud() methods in NumPy including their effects on various array dimensons.**

In [ ]:
#In NumPy, `fliplr()` and `flipud()` are functions used to flip arrays in different directions:

### `fliplr()`
'''Purpose: Flips an array from left to right (horizontal flip).
Input: Works on 2D arrays (matrices) and can be applied to higher-dimensional arrays as well, flipping the last axis.'''

#### Example:
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Flip left to right
flipped_lr = np.fliplr(array_2d)

print("Original Array:")
print(array_2d)

print("\nFlipped Left to Right:")
print(flipped_lr)


#### Output:
'''
Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped Left to Right:
[[3 2 1]
 [6 5 4]
 [9 8 7]]
'''

###`flipud()`
'''Purpose: Flips an array from up to down (vertical flip).
Input: Primarily operates on 2D arrays, flipping the first axis.'''

#### Example:
# Flip up to down
flipped_ud = np.flipud(array_2d)

print("\nFlipped Up to Down:")
print(flipped_ud)


#### Output:
'''
Flipped Up to Down:
[[7 8 9]
 [4 5 6]
 [1 2 3]]
'''

### Differences
#1.Direction of Flip:
'''`fliplr()`: Flips the array horizontally (left to right).
`flipud()`: Flips the array vertically (up to down).'''

#2.Effect on Array Dimensions:
'''2D Arrays: Both functions will change the arrangement of elements, but `fliplr()` changes columns, while `flipud()` changes rows.
1D Arrays: Neither function applies directly, but you can use `fliplr()` as a special case that effectively behaves
like a reverse operation for a 1D array.
Higher-Dimensional Arrays: Both functions operate on the last axis for `fliplr()` and the first axis for `flipud()`,
meaning they can affect multi-dimensional arrays while maintaining the structure of other axes.'''

### Summary
'''Use `fliplr()` when you want to mirror an array horizontally.
Use `flipud()` when you want to mirror an array vertically.
Both functions are useful for data manipulation and transformation in various contexts.'''

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped Left to Right:
[[3 2 1]
 [6 5 4]
 [9 8 7]]

Flipped Up to Down:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


'Use `fliplr()` when you want to mirror an array horizontally.\nUse `flipud()` when you want to mirror an array vertically.\nBoth functions are useful for data manipulation and transformation in various contexts.'

Q-9 **Discuss the functionality of the array_split() method in NumPy . How does it handles uneven splits?**

In [ ]:
'''The `array_split()` function in NumPy is used to divide an array into multiple sub-arrays.
It provides more flexibility than the `split()` method because it allows for uneven splits.'''

### Functionality of `array_split()`

#Basic Syntax:
'''numpy.array_split(ary, indices_or_sections, axis=0)
`ary`: The input array to be split.
`indices_or_sections`: Can be an integer (indicating the number of equal sections) or a list of indices where the array should be split.
`axis`: The axis along which to split the array. Default is 0 (row-wise).'''

### How It Handles Uneven Splits

'''When using `array_split()` with an integer as `indices_or_sections`,
NumPy will attempt to divide the array into the specified number of equal sections.
If the array cannot be evenly divided (for example, when the length of the array is not perfectly divisible by the number of sections),
NumPy will distribute the extra elements among the resulting sub-arrays.'''

#### Example of Uneven Splits

import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7])

# Split the array into 3 sections
result = np.array_split(array_1d, 3)

print("Original Array:")
print(array_1d)

print("\nSplit Result:")
for idx, arr in enumerate(result):
    print(f"Sub-array {idx}: {arr}")


### Key Points
'''Uneven Distribution: In the example, the original array of length 7 was split into 3 parts.
The first part received 3 elements, while the next two parts received 2 and 2 elements, respectively.
Higher Dimensions: `array_split()` can also be used on 2D and higher-dimensional arrays,
allowing for splitting along different axes.'''

#### Example with 2D Array

# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9],
                     [10, 11, 12]])

# Split the array into 3 sections along the first axis
result_2d = np.array_split(array_2d, 3, axis=0)

print("\n2D Array Split Result:")
for idx, arr in enumerate(result_2d):
    print(f"Sub-array {idx}:\n{arr}")


### Summary
'''`array_split()` is a versatile function that allows for splitting arrays into multiple sub-arrays, even if the splits cannot be perfectly equal.
When the total number of elements cannot be evenly divided,
it distributes the remainder across the resulting sub-arrays,
ensuring that all elements are included in the output.'''

Original Array:
[1 2 3 4 5 6 7]

Split Result:
Sub-array 0: [1 2 3]
Sub-array 1: [4 5]
Sub-array 2: [6 7]

2D Array Split Result:
Sub-array 0:
[[1 2 3]
 [4 5 6]]
Sub-array 1:
[[7 8 9]]
Sub-array 2:
[[10 11 12]]


'`array_split()` is a versatile function that allows for splitting arrays into multiple sub-arrays, even if the splits cannot be perfectly equal.\nWhen the total number of elements cannot be evenly divided, \nit distributes the remainder across the resulting sub-arrays,\nensuring that all elements are included in the output.'

Q-10 **Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?**

In [ ]:
'''Vectorization and broadcasting are two powerful concepts in NumPy that contribute significantly
to the efficiency of array operations. Here’s a detailed look at each concept:'''

### Vectorization

#Definition:
'''Vectorization refers to the process of converting operations that would typically
be performed in a loop into array-based operations. In NumPy, this means applying operations directly to whole arrays or large chunks
of data rather than iterating through elements one at a time.'''

#Benefits:
'''1.Performance: Vectorized operations are usually faster because they leverage low-level optimizations and are implemented in C,
 allowing for more efficient computation.
2.Conciseness: Code is more readable and compact, as it avoids explicit loops.'''

#### Example of Vectorization:
import numpy as np

# Create two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vectorized addition
result = a + b  # No loop is needed

print(result)  # Output: [5 7 9]


#In this example, the addition operation is applied to the entire arrays at once rather than element by element.

### Broadcasting

#Definition:
'''Broadcasting is a technique used in NumPy to perform arithmetic operations on arrays of different shapes.
When two arrays have different shapes,
NumPy automatically "broadcasts" the smaller array across the larger one so that they can be made compatible for element-wise operations.'''

#Rules:
'''1.If the arrays have the same number of dimensions, they must be compatible in
all dimensions (either the dimensions are equal or one of them is 1).
2.If the arrays have a different number of dimensions, the smaller-dimensional array is
padded with ones on its left side until both arrays have the same number of dimensions.'''

#### Example of Broadcasting:

# Create a 2D array and a 1D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

array_1d = np.array([10, 20, 30])

# Broadcasting the 1D array to add to the 2D array
result_broadcast = array_2d + array_1d

print(result_broadcast)


'''In this example, `array_1d` is broadcasted across `array_2d`.
NumPy effectively treats the 1D array as if it were reshaped to match the shape of the 2D array, allowing for seamless addition without explicit looping.'''

### Contributions to Efficient Array Operations

'''1.Reduced Overhead: By eliminating the need for Python loops,
both vectorization and broadcasting minimize the overhead associated with Python’s interpreted execution. This results in faster computations.

2.Memory Efficiency: Broadcasting allows operations to be performed without creating large temporary arrays,
 which conserves memory and reduces the computational cost.

3.Improved Code Readability: Both concepts lead to clearer and more maintainable code. Operations become more intuitive,
 focusing on what is being computed rather than how it is implemented.

4.Optimized Libraries: NumPy's underlying implementations are highly optimized, and leveraging vectorization
and broadcasting allows users to take full advantage of these optimizations for large datasets.'''

### Summary
'''Vectorization simplifies and accelerates array operations by applying functions to entire arrays at once.
Broadcasting enables operations between arrays of different shapes without needing explicit reshaping, making computations more flexible and efficient.
Together, they are fundamental to NumPy’s performance and ease of use, allowing for powerful data manipulation and analysis with minimal code.'''

[5 7 9]
[[11 22 33]
 [14 25 36]]


'Vectorization simplifies and accelerates array operations by applying functions to entire arrays at once.\nBroadcasting enables operations between arrays of different shapes without needing explicit reshaping, making computations more flexible and efficient.\nTogether, they are fundamental to NumPy’s performance and ease of use, allowing for powerful data manipulation and analysis with minimal code.'

*Create a 3x3 NumPy array with random integers between 1 to 100.Then , interchange its rows and columns*

In [34]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(array)

# Interchange rows and columns (transpose the array)
transposed_array = array.T
print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[ 1 91 30]
 [36 85 50]
 [48 85 50]]

Transposed Array:
[[ 1 36 48]
 [91 85 85]
 [30 50 50]]


*Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array , then into a 5x2 array*

In [35]:
import numpy as np

# Generate a 1D array with 10 elements
array_1d = np.arange(10)  # This creates an array with values from 0 to 9
print("1D Array:")
print(array_1d)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\n2x5 Array:")
print(array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\n5x2 Array:")
print(array_5x2)


1D Array:
[0 1 2 3 4 5 6 7 8 9]

2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


*Create a 4x4 NumPy array with NumPy array with random float values
. Add a border of zeros around it.resulting in a 6x6 array*

In [36]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(array_4x4)

# Add a border of zeros around the array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Border of Zeros:")
print(array_with_border)


Original 4x4 Array:
[[0.3235948  0.68725596 0.03035268 0.30651149]
 [0.32381046 0.20760116 0.86964075 0.67788152]
 [0.67971678 0.73857988 0.56587166 0.99841965]
 [0.02338909 0.76801215 0.93130251 0.03073119]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.3235948  0.68725596 0.03035268 0.30651149 0.        ]
 [0.         0.32381046 0.20760116 0.86964075 0.67788152 0.        ]
 [0.         0.67971678 0.73857988 0.56587166 0.99841965 0.        ]
 [0.         0.02338909 0.76801215 0.93130251 0.03073119 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


*Create a NumPy array of strings ['python' 'numpy' 'pandas'] . Apply different case transformations (uppercase,lowercase,titlecase,etc.)to each element.*

In [37]:
import numpy as np

# Create a NumPy array of strings
array_strings = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = np.char.upper(array_strings)
lowercase = np.char.lower(array_strings)
titlecase = np.char.title(array_strings)
capitalize = np.char.capitalize(array_strings)

# Print the results
print("Original Array:")
print(array_strings)

print("\nUppercase:")
print(uppercase)

print("\nLowercase:")
print(lowercase)

print("\nTitlecase:")
print(titlecase)

print("\nCapitalized:")
print(capitalize)


Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Titlecase:
['Python' 'Numpy' 'Pandas']

Capitalized:
['Python' 'Numpy' 'Pandas']


*Generate a NumPy array of words. Insert a space between each character of every word in the arry*

In [38]:
import numpy as np

# Create a NumPy array of words
array_words = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', array_words)

# Print the results
print("Original Array:")
print(array_words)

print("\nArray with Spaces Between Characters:")
print(spaced_words)


Original Array:
['python' 'numpy' 'pandas']

Array with Spaces Between Characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


*Create two 2D NumPy arrays and perform element-wise addition,substraction,multiplication,and division.*

In [39]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

# Print the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


*Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.*

In [40]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


*Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array*

In [41]:
import numpy as np

# Generate an array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)
print("Random Integers:")
print(random_integers)

# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Find and display all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]
print("\nPrime Numbers:")
print(prime_numbers)


Random Integers:
[838 563 807 874 634 958 120  65  23 460 657 177 405 136 473 797 836  97
 823 414 304  34 681 581 495 271 338 906 827 602 900 427 296 197 147 749
  22 439 493 159 400 803 696 273 819 705 429 981 944  75 123   9 983 867
 863 324 223 935 221 545 531 215 809 951 560 167 193 188  70 527 110  46
 772 529 894 949 553 932 608 145 473 528 936 963 559 361 717   2 144 970
 202 243 590  99 831 948 529 911 807 727]

Prime Numbers:
[563, 23, 797, 97, 823, 271, 827, 197, 439, 983, 863, 223, 809, 167, 193, 2, 911, 727]


*Create a NumPy array representing daily temparature for a month. Calculate and display the weekly averages.*

In [55]:
import numpy as np

def generate_daily_temperatures(days=30, low=15, high=30):
    """
    Generate random daily temperatures for a given number of days.

    Parameters:
        days (int): Number of days to generate temperatures for.
        low (int/float): Minimum possible temperature.
        high (int/float): Maximum possible temperature.

    Returns:
        np.ndarray: Array of daily temperatures.
    """
    return np.random.uniform(low, high, size=days)

def calculate_weekly_averages(temperatures, days_per_week=7):
    """
    Calculate weekly averages from an array of temperatures.

    Parameters:
        temperatures (np.ndarray): Array of daily temperatures.
        days_per_week (int): Number of days in a week.

    Returns:
        list: List of weekly averages.
    """
    weeks = np.array_split(temperatures, range(days_per_week, len(temperatures), days_per_week))
    return [np.mean(week) for week in weeks]

# Generate daily temperatures for 30 days
daily_temperatures = generate_daily_temperatures()

# Calculate weekly averages
weekly_averages = calculate_weekly_averages(daily_temperatures)

# Display results
print("Daily Temperatures (°C):", daily_temperatures)
print("Weekly Averages (°C):", weekly_averages)


Daily Temperatures (°C): [28.38704087 21.95257833 27.65687257 20.44124235 15.43874824 17.63934134
 22.90999121 19.94504807 29.09204764 25.7966829  24.68921167 16.73350901
 19.96302093 20.44814864 19.71736751 20.19355009 16.14147138 26.31321776
 15.35067648 24.28863209 17.23222348 28.80813403 15.11429722 26.17297905
 28.9446381  22.14347755 20.63971667 29.1936926  26.52597677 19.47647192]
Weekly Averages (°C): [22.06083070161845, 22.381095553441547, 19.89101982724852, 24.43099074693435, 23.001224348834345]
